### PR TITLE
Fix/cities input

### LINKED ISSUE #194: Activer la liste des villes par un clic
### Current Behavior 

Quand on a entré le nom d'une ville et qu'on a fait disparaître la liste des villes (touche Esc ou clic à côté), on ne peut réafficher la liste des villes qu'en retapant le nom de la ville (ou en supprimant le dernier caractère)

### Expected Behaviour 

Il faudrait pouvoir réafficher la liste des villes en cliquant sur le champ déjà rempli. 

### Steps to Reproduce the Problem  

taper "Lyon" dans la ville de départ, ne pas sélectionner la ville dans la liste, appuyer sur la touche Esc pour faire disparaître la liste, cliquer dans le champ de la ville de départ : il ne se passe rien. 

[x] Development
[x] Production

### Ideas for solving the problem / Implementing the new functionality  

?

### PR DESCRIPTION
**Pull request by nicolasleger**
This PR regroup all fixes around cities input.

**TODO: We need to better design the error on each field and/or both.**

# Changes

- Search Date input display with day
- Cities list on focus
- Auto select first city on ENTER
- Error displayed when search without city selection
- Auto propose main cities when city search < 2 characters
- Paragraph help for search on homepage

screen shot 2017-10-21 at 11 46 27

# Issues

- https://github.com/covoiturage-libre/covoiturage-libre/issues/130 Sélection des villes : pb d'ergonomie
- https://github.com/covoiturage-libre/covoiturage-libre/issues/116 champ villes pour la recherche
- https://github.com/covoiturage-libre/covoiturage-libre/issues/194 Activer la liste des villes par un clic
- https://github.com/covoiturage-libre/covoiturage-libre/issues/193 Enchaînement de recherches : la recherche précédente est réaffichée si on écrit une ville de départ sans sélectionner dans la liste

- https://github.com/covoiturage-libre/covoiturage-libre/issues/184 Ajouter le jour de la semaine dans les résultats de la recherche (et consultation d'annonce)
- https://github.com/covoiturage-libre/covoiturage-libre/issues/192 Pas de résultats : être plus+ précis

# Testing

https://cl-fix-cities-input.herokuapp.com/

- Empty city https://cl-fix-cities-input.herokuapp.com/recherche?utf8=%E2%9C%93&search%5Bfrom_city%5D=&search%5Bfrom_lon%5D=&search%5Bfrom_lat%5D=&search%5Bto_city%5D=Pa&search%5Bto_lon%5D=&search%5Bto_lat%5D=48.866667&search%5Bdate%5D=&commit=Partez+%21

# Original Pull Requests

## From PR https://github.com/covoiturage-libre/covoiturage-libre/pull/195

C'est mon premier PR ! :)

### What does/resolve this PR? 
'Activer la liste des villes par un clic' #194 'Enchaînement de recherches' #193 ; 'Pas de résultats : être plus+ précis' #192 ; 'séparation visuelle entre les résultats 'le jour recherché' et 'les jours ultérieurs'' #184

### What does/resolve this PR? 
General ergonomy. This adds autocomplete when not typing full city name and clicking directly on next field.
When city field looses focus it tries to autocomplete the Name, latitude and longitude. This limits the blank page results. Solves #130 and hopefully #116.

EDIT: this PR also resolves #194 !! The city menu reopens when focused.

And you should test it at:
https://covoli-dev-pr214.scalingo.io/

- Test of https://github.com/covoiturage-libre/covoiturage-libre/issues/116
https://covoli-dev-pr214.scalingo.io/recherche?utf8=%E2%9C%93&search%5Bfrom_city%5D=xxx&search%5Bfrom_lon%5D=&search%5Bfrom_lat%5D=&search%5Bto_city%5D=yyy&search%5Bto_lon%5D=&search%5Bto_lat%5D=&search%5Bdate%5D=30%2F12%2F2016&commit=Rechercher

### CODE REVIEW

File: app/assets/javascripts/_init-autocomplete.js [hunk 1]
```diff
@@ -1,9 +1,18 @@
 jQuery.fn.extend({
   geonameAutocomplete: function () {
     return this.autocomplete({
-      minLength: 2,
-      source: function (request, response) {
-        $.getJSON("/cities/autocomplete?term=" + request.term, function (data) {
+      minLength: 0,
+      // automatically focus first item from autocomplete menu
+      autoFocus: true,
+      source: function(request, response) {
```
Comment (webplate) [inline app/assets/javascripts/_init-autocomplete.js]: OK to use old js syntax if you must (a bit odd that heroku is so old school)

File: app/assets/javascripts/_init-autocomplete.js [hunk 2]
```diff
@@ -1,9 +1,18 @@
...
+        var listUri;
+        if (request.term.length < 2) {
```
Comment (webplate) [inline app/assets/javascripts/_init-autocomplete.js]: I don't think it should be implemented like that or it needs further work. When I type "P" I get Paris (nice but it's showing two times ??!!). Problem is that when I type "Paris" the first selected item reverses to Parisot. It's really troubling.
citiy complete
 Maybe we should put an exact match always first ?

File: app/assets/javascripts/_init-autocomplete.js [hunk 3]
```diff
@@ -12,32 +21,62 @@ jQuery.fn.extend({
...
+      select: function(event, ui) {
         // by default the change event is not triggered on hidden input fields
         // we need it to update the map instantly
-        $('#' + this.id.replace(/city/, 'lat')).val(ui.item.lat).trigger('change');
-        $('#' + this.id.replace(/city/, 'lon')).val(ui.item.lon).trigger('change');
+        var lat = $("#" + this.id.replace(/city/, "lat"));
+        var lon = $("#" + this.id.replace(/city/, "lon"));
+        lat.val(ui.item.lat).trigger("change");
+        lon.val(ui.item.lon).trigger("change");
+        $(this).parent().removeClass('has-error');
```
Comment (webplate) [inline app/assets/javascripts/_init-autocomplete.js]: We try to use double quotes in the project's JS

File: app/controllers/cities_controller.rb [hunk 4]
```diff
@@ -1,14 +1,34 @@
...
+    Montpellier
+    Bordeaux
+  )
+
   def autocomplete
     @results = City.search(
       params[:term],
       limit: 5,
-      boost_where: {country_code: {value: 'FR', factor: 5}},
+      boost_where: { country_code: { value: 'FR', factor: 5 } },
```
Comment (webplate) [inline app/controllers/cities_controller.rb]: Ideally, we would boost the city according to its population (and we would not need a hardcoded MAIN_CITIES). Population was in geoname DB but I'm not sure it's imported in our project.

File: app/controllers/cities_controller.rb [hunk 5]
```diff
@@ -1,14 +1,34 @@
 class CitiesController < ApplicationController
 
+  # TOP 10 FR by population
+  MAIN_CITIES = %w(
```
Comment (webplate) [inline app/controllers/cities_controller.rb]: Maybe this hardcoded list isn't needed (see idea below)

File: app/views/search/_form.html.haml [hunk 6]
```diff
@@ -1,6 +1,13 @@
 - input_class = large_inputs ? 'input-lg' : ''
 - btn_class = large_inputs ? 'btn-lg' : ''
 
+%p Écrivez puis sélectionnez dans la liste :
+%ul
+  %li une ville de départ et une ville d'arrivée
+  %li ou seulement une ville de départ
+  %li ou seulement une ville d'arrivée
+%p Le moteur va rechercher à 25km près
```
Comment (webplate) [inline app/views/search/_form.html.haml]: I wouldn't add this as it's prone to change and implicit

File: app/views/search/_form.html.haml [hunk 7]
```diff
@@ -1,6 +1,13 @@
 - input_class = large_inputs ? 'input-lg' : ''
 - btn_class = large_inputs ? 'btn-lg' : ''
 
+%p Écrivez puis sélectionnez dans la liste :
```
Comment (webplate) [inline app/views/search/_form.html.haml]: These instructions are pretty long and most of it is implicit. Could be replaced by a line in FAQ or a help popup for less pollution in main page.

File: app/views/search/_form.html.haml [hunk 8]
```diff
@@ -33,3 +42,32 @@
...
+      if (emptyCityGeoCount > 2) { // No city fully selected with geo
+        var input = $('#search_to_city');
+
+        // Display error
+        input.parent().addClass('has-error');
+        var inputHelpBlock = input.next('.help-block');
+        if (inputHelpBlock.length > 0) {
+          inputHelpBlock.show();
+        } else { // Create it
+          $("<span>", {
```
Comment (webplate) [inline app/views/search/_form.html.haml]: As you said it, this looks too ugly for deployment. Could avoid repetition with l 47 and l 50 of search.rb (same message in 3 places)

File: app/views/trips/_trip.html.haml [hunk 9]
```diff
@@ -1,18 +1,21 @@
...
       .info
         .name= trip.name
         .age= "#{trip.age} ans" if trip.age.present?
     .trip-info
       .title
-        =l trip.departure_date, format: :long
+        =l trip.departure_date, format: :trip_date
         =l trip.departure_time, format: :short
+        %p= "(le covoit' est déjà parti !)" if (trip.is_before_today?) 
+        %p= "/!\\ départ dans #{Integer(trip.departure_date - @search.date_value)} jour(s)" if (trip.is_strictly_before(@search.date_value))
```
Comment (webplate) [inline app/views/trips/_trip.html.haml]: Does this outputs negative time intervals ? In that case I see the better option:Départ x jours avant votre recherche.

File: app/assets/javascripts/_init-autocomplete.js (hunk 1 above)
Comment (nicolasleger) [reply app/assets/javascripts/_init-autocomplete.js]: Asset compilation error, see comments on https://github.com/covoiturage-libre/covoiturage-libre/pull/214

File: app/assets/javascripts/_init-autocomplete.js (hunk 2 above)
Comment (nicolasleger) [reply app/assets/javascripts/_init-autocomplete.js]: Sorry, I added cities multiple times on test env, fixe.

File: app/assets/javascripts/_init-autocomplete.js (hunk 3 above)
Comment (nicolasleger) [reply app/assets/javascripts/_init-autocomplete.js]: Yes you're absolutely right, I will edit it.

File: app/controllers/cities_controller.rb (hunk 4 above)
Comment (nicolasleger) [reply app/controllers/cities_controller.rb]: Yes, but we haven't yet the population in our DB.
Another plus would be to propose main cities around the IP by default before user tipped 2 characters.
Linked with the " Dépôt d'annonce: suggestion d'étapes " https://github.com/covoiturage-libre/covoiturage-libre/issues/212

Until done we can start with a hard coded list.

File: app/views/search/_form.html.haml (hunk 7 above)
Comment (nicolasleger) [reply app/views/search/_form.html.haml]: I think too.
It was suggested by https://github.com/djakk in his/her PR https://github.com/covoiturage-libre/covoiturage-libre/pull/195
We have to decide with others.

File: app/views/search/_form.html.haml (hunk 8 above)
Comment (nicolasleger) [reply app/views/search/_form.html.haml]: True ! I will clean this up.

File: app/views/trips/_trip.html.haml (hunk 9 above)
Comment (nicolasleger) [reply app/views/trips/_trip.html.haml]: For the negative, there is the `is_strictly_before ` and search filters all trips before selected date.
But it could be a good idea if no result returned to display them with a message liek that.

**Comment by nicolasleger** [comment]
@webplate you're right about the too much of this PR
however I think functional issues are very linked
like your PR and djakk one

File: app/assets/javascripts/_init-autocomplete.js (hunk 2 above)
Comment (webplate) [reply app/assets/javascripts/_init-autocomplete.js]: What I meant: For example on Paris:
Typing "P" gives Paris, but typing "Pa" gives Parisot and further letters won't change the order (typing "Paris" gives Parisot).
I think we should boost main cities even when more than one letter is entered and especially if we have an exact match with the name.

File: app/controllers/cities_controller.rb (hunk 4 above)
Comment (webplate) [reply app/controllers/cities_controller.rb]: Not optimal but you're right until then (would be cool to have a nice city DB with extra properties like population for interesting search / suggestions).
Good point of this hard-coded implementation is that it's fast, and it's certainly a must for the main input.

File: app/views/search/_form.html.haml (hunk 7 above)
Comment (webplate) [reply app/views/search/_form.html.haml]: @AlexBillbao , @djakk, @maxb29, @ndelavergne ? What's your opinion about these instructions on the main page ?

File: app/assets/javascripts/_init-autocomplete.js (hunk 2 above)
Comment (nicolasleger) [reply app/assets/javascripts/_init-autocomplete.js]: Ok good idea, check or create an issue for it, linked to suggested cities.

**Comment by webplate** [comment]
I approve this PR's code, but I think it shouldn't contain all or most of the main page help messages. The error messages need a rework too.

**Comment by webplate** [comment]
I'll try to implement better use of the MAIN_CITIES list in another PR.
See https://github.com/covoiturage-libre/covoiturage-libre/pull/215#discussion_r146135790

**Comment by nicolasleger** [comment]
@webplate I juste clean the code a bit.
I propose to wait for the validation or not of messages and error wording.

Then push current `master` modifications on the official dev env so some users can test changes.

File: app/views/search/_form.html.haml (hunk 7 above)
Comment (djakk) [reply app/views/search/_form.html.haml]: @webplate @nicolasleger I like when it is verbose :) but maybe the red error message "sélectionnez une ville *dans* la liste" is enough

Comment (djakk) [reply app/views/search/_form.html.haml]: Sinon maxb29 propose : 
"Écrivez puis sélectionnez dans la liste:
Une ville de départ et/ou une ville d'arrivée"
